# Generated by Django 4.2.2 on 2023-06-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_rename_blogmodel_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title_tag',
            field=models.CharField(default='Blog', max_length=255),
        ),
    ]
