# Generated by Django 4.2.2 on 2023-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_posts_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
