# Generated by Django 4.2.2 on 2023-06-19 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_alter_posts_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
